<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MissionRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class MissionRepository extends EntityRepository
{
    public function getMissionToDay()
    {
        $query = $this->createQueryBuilder("m");
        $query
            ->where("m.date = :date")
            ->setParameter("date",(new \DateTime())->format("Y-m-d"));
        return $query->getQuery()->getResult();
    }
    public function getMissionTomorrow()
    {
        $query = $this->createQueryBuilder("m");
        $query
            ->where("m.date = :date")
            ->setParameter("date",(new \DateTime())->modify("+1 day")->format("Y-m-d"));
        return $query->getQuery()->getResult();
    }
}
