<?php

namespace AppBundle\Repository;

/**
 * RemorqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RemorqueRepository extends \Doctrine\ORM\EntityRepository
{
}
