<?php

namespace AppBundle\Repository;

/**
 * TypeEntretientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeEntretientRepository extends \Doctrine\ORM\EntityRepository
{
}
