<?php

namespace AppBundle\Repository;

/**
 * VehiculeOccupationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VehiculeOccupationRepository extends \Doctrine\ORM\EntityRepository
{
}
