<?php

namespace AppBundle\Repository;

/**
 * VisiteTechniqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VisiteTechniqueRepository extends \Doctrine\ORM\EntityRepository
{

    public function getVisiteThisMonthVehicule()
    {
        $query =$this->createQueryBuilder("v");
        $query
            ->where($query->expr()->isNotNull("v.vehicule"))
            ->andWhere($query->expr()->between("v.prochaineDate",":debut",":fin"))
            ->setParameters(array(
                'debut'=>date('Y-m-01'),
                'fin'=>date('Y-m-t'),
            ))
        ;
        return $query->getQuery()->getResult();
    }

    public function getVisiteThisMonthRemorque()
    {
        $query =$this->createQueryBuilder("v");
        $query
            ->where($query->expr()->isNotNull("v.remorque"))
            ->andWhere($query->expr()->between("v.prochaineDate",":debut",":fin"))
            ->setParameters(array(
                'debut'=>date('Y-m-01'),
                'fin'=>date('Y-m-t'),
            ))
        ;
        return $query->getQuery()->getResult();
    }
}
